[package]
authors.workspace = true
edition.workspace = true
name = "kellnr"
version = "0.1.0"
license-file = "../../LICENSE"

[dependencies]
# Internal dependencies from Kellnr
common.workspace = true
db.workspace = true
docs.workspace = true
index.workspace = true
settings.workspace = true
web_ui.workspace = true
registry.workspace = true
appstate.workspace = true
storage.workspace = true
auth.workspace = true

# External dependencies from crates.io
tracing.workspace = true
tracing-subscriber.workspace = true
flume.workspace = true
axum.workspace = true
axum-extra.workspace = true
tower-http.workspace = true
tokio.workspace = true
openssl = { version = "*", optional = true } # Not needed directly but for cross-compilation with the vendored-openssl feature
once_cell = "1.19.0"

[features]
vendored-openssl = ["openssl/vendored"]

# Ignore openssl in cargo machete, else
# "cargo machete" will show openssl as an unused depedenency
[package.metadata.cargo-machete]
ignored = ["openssl"]
