[workspace]
exclude = [
  "crates/test_data",
]
members = [
  "crates/*",
  "crates/db/entity",
  "crates/db/migration",
]
default-members = [ "crates/kellnr" ]
resolver = "2"

  [workspace.package]
  authors = [ "kellnr.io" ]
  edition = "2021"
  version = "0.1.0"
  license-file = "LICENSE"

  [workspace.dependencies]
  # Internal dependencies from Kellnr
  common = { path = "./crates/common" }
  db = { path = "./crates/db" }
  entity = { path = "./crates/db/entity" }
  migration = { path = "./crates/db/migration" }
  docs = { path = "./crates/docs" }
  index = { path = "./crates/index" }
  settings = { path = "./crates/settings" }
  web_ui = { path = "./crates/web_ui" }
  registry = { path = "./crates/registry" }
  pg_testcontainer = { path = "./crates/db/pg_testcontainer" }
  auth = { path = "./crates/auth" }
  error = { path = "./crates/error" }
  appstate = { path = "./crates/appstate" }
  storage = { path = "./crates/storage" }

  # External dependencies from crates.io
  anyhow = "1.0.75"
  jsonwebtoken = "9.1.0"
  reqwest = { version = "0.11.22", features = [ "json", "blocking" ] }
  serde = { version = "1.0.193", features = [ "derive" ] }
  sysinfo = "0.30.5"
  semver = "1.0.19"
  regex = "1.8.3"
  serde_json = "1.0.108"
  mockall = "0.12.0"
  rand = "0.8.5"
  chrono = "0.4.31"
  hex = "0.4.3"
  sha2 = "0.10.8"
  sea-orm = { version = "0.12.7", features = [
    "sqlx-postgres",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
  ] } # Must not upgrade sea-orm to 0.12.3 as that breaks migrations for sqlite
  thiserror = "1.0.50"
  sea-query = "0.30.3"
  sea-query-derive = "0.4.1"
  sea-orm-migration = { version = "0.12.6", features = [
    "sqlx-postgres",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
  ] }
  rm_rf = "0.6.2"
  testcontainers = "0.15.0"
  quote = "1.0.33"
  syn = { version = "2.0.39", features = [ "full" ] }
  trybuild = { version = "1.0.85", features = [ "diff" ] }
  zip = "0.6.6"
  flate2 = "1.0.28"
  tar = "0.4.40"
  cargo = "0.76.0"
  fs_extra = "1.3.0"
  wax = "0.6.0"
  proc-macro2 = "1.0.70"
  moka = { version = "0.12.1", features = [ "future" ] }
  config = "0.14.0"
  toml = "0.8.1"
  time = "0.3.29"
  tracing = "0.1.40"
  tracing-subscriber = { version = "0.3.17", features = [ "json", "fmt" ] }
  flume = "0.11.0"
  axum = { version = "0.7.1", features = [ "macros" ] }
  axum-extra = { version = "0.9.0", features = [
    "cookie",
    "cookie-private",
    "typed-header",
  ] }
  tokio = { version = "1.32.0", features = [
    "macros",
    "rt-multi-thread",
    "process",
  ] }
  tower = { version = "0.4.13", features = [ "util" ] }
  hyper = "1.0.1"
  tower-http = { version = "0.5.0", features = [ "fs", "trace" ] }
  cookie = { version = "0.18.0", features = [ "private", "percent-encode" ] }
  futures = "0.3.29"
  http-body-util = "0.1.0"

[profile.release]
lto = "thin"
strip = true

# Profile for the CI build in "release"
# to build as fast as possible
[profile.ci-release]
inherits = "release"
incremental = false

# Profile for the CI build in "debug"
# to build as fast as possible
[profile.ci-dev]
inherits = "dev"
incremental = false
lto = "off"
